### ISSUE TITLE
Feature Request Website

### ISSUE THREAD

**Issue by empea-careercriminal** [BotGarage/ideation#13]
Feature Description: Implement a web frontend that ingests feature requests and creates issues thereof 

Acceptance Criteria:

- [ ] Build a simple web frontend that provides a conversational chat that discusses feature requests with a user
- [ ] Generate a Github issue from the result of the conversation and presents it to the user for sanity checking and optional editing of the issue
- [ ] Send it to the Github API to create the issue within the [BotGarage/ideation](https://github.com/BotGarage/ideation) repository

**Comment by boorich** [comment]
**Idea**
Generate prompts (and later code) to automagically create the requested features as a module, so that people can basically say what they want and get this generated.

**Comment by empea-careercriminal** [comment]
**Feature Description:**
Implement a user authentication system for a web application.

**Acceptance Criteria:**
- [ ] Users should be able to register with their email and create a password.
- [ ] Registered users should be able to log in and access their account.
- [ ] Passwords must be securely hashed and stored.
- [ ] Users should receive a confirmation email upon registration.
- [ ] Users should be able to reset their password if forgotten.
